FROM ubuntu:focal 

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y tini \
    libasound2-plugins avahi-daemon flac \
    apulse libopus0 libvorbis0a libsoxr0 libavahi-client3 && \
    rm -rf /var/lib/apt/lists/*


COPY --from=docker.io/grewhit25/debian-snapcast /usr/local/bin/snapclient /usr/local/bin/
COPY --from=docker.io/grewhit25/debian-snapserver /usr/local/bin/check /
COPY entrypoint.sh /
COPY asound.conf /etc/

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["tini", "--", "/entrypoint.sh"]
CMD ["snapclient"]