FROM alpine:edge

ENV TZ London/Europe
WORKDIR /data

# Create server client from source

RUN apk -U add --virtual .build-deps git bash build-base asio-dev soxr-dev \
    avahi-dev flac-dev libvorbis-dev alsa-lib-dev opus opus-dev \
 && cd /root \
 && git clone https://github.com/badaix/snapcast.git \
 && cd snapcast/externals \
 && git submodule update --init --recursive \
 && cd .. \
 && make -j $(grep -c ^processor /proc/cpuinfo) \
 && cp server/snapserver client/snapclient /usr/local/bin \
 && cd / \
 && apk --purge del .build-deps \
 && rm -rf /etc/ssl /var/cache/apk/* /lib/apk/db/* /root/snapcast

USER root


