FROM ubuntu:focal 

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y tini \
    libasound2-plugins avahi-daemon flac \
    apulse libopus0 libvorbis0a libsoxr0 libavahi-client3 && \
    rm -rf /var/lib/apt/lists/*


COPY --from=localhost/snapcast-debian /usr/local/bin/snapclient /usr/local/bin/
COPY entrypoint.sh /
COPY asound.conf /etc/

ENTRYPOINT ["tini", "--", "/entrypoint.sh"]
CMD ["snapclient"]