FROM golang as builder
#
# Install health check
# credit to https://github.com/meisterplan/k8s-health-check.git
RUN go get github.com/grewhit25/k8s-health-check
WORKDIR  /go/src/github.com/grewhit25/k8s-health-check
RUN make build
#RUN make test

FROM ubuntu:focal
# Install snapcast server
LABEL MAINTAINER="Greg White grewhit25@gmail.com"
# v0.20.1
ARG S6_ARCH='aarch64'
ARG S6_VERSION='2.0.0.1'

# Install dependences
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y wget avahi-daemon libavahi-client3 \
    libvorbisenc2 flac libopus0  && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/* /var/tmp/* && \
    mkdir /health && touch /health/healthz

# Install s6 overlay
# https://github.com/just-containers/s6-overlay/issues/239 - S6 workaround
#ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_VERSION}/s6-overlay-${S6_ARCH}.tar.gz /tmp/s6-overlay.tar.gz
RUN ARCH="$(uname -m)" && \
    if [ "${ARCH}" = 'armv7l' ]; then ARCH = 'armhf'; \
    elif [ "${ARCH}" = 'x86_64' ]; then ARCH = 'x86'; \
    fi; \
    wget -q -O /tmp/s6-overlay.tar.gz https://github.com/just-containers/s6-overlay/releases/download/v${S6_VERSION}/s6-overlay-${ARCH}.tar.gz
RUN tar xzf /tmp/s6-overlay.tar.gz -C / --exclude="./bin" && \
    tar xzf /tmp/s6-overlay.tar.gz -C /usr ./bin


# Copy in s6 and prebuilt binaries
COPY root /
COPY *.conf /etc/
COPY --from=builder /go/src/github.com/grewhit25/k8s-health-check/check /usr/local/bin/
COPY --from=docker.io/grewhit25/debian-snapcast /usr/local/bin/snapserver /usr/local/bin/
COPY --from=docker.io/grewhit25/debian-librespot /usr/local/bin/librespot /usr/local/bin/

# Snapcast Ports
EXPOSE 1704 1705
VOLUME /output

ENTRYPOINT ["/init"]