FROM golang as builder
#
# Install health check
# credit to https://github.com/meisterplan/k8s-health-check.git
RUN go get github.com/grewhit25/k8s-health-check
WORKDIR  /go/src/github.com/grewhit25/k8s-health-check
RUN make build

FROM ubuntu:focal
# Install snapcast server
LABEL MAINTAINER="Greg White grewhit25@gmail.com"
# v0.22.0
ARG S6_VERSION='2.1.0.0'

# Install s6 overlay
RUN apt-get update && apt-get install -y \
    wget && \
    set -ex; \
    ARCH="$(uname -m)"; \
    if [ "$ARCH" = 'armv7l' ]; then ARCH='armhf'; \
    elif [ "$ARCH" = 'x86_64' ]; then ARCH='x86'; \
    fi; \
    wget --no-check-certificate -qO /tmp/s6-overlay.tar.gz https://github.com/just-containers/s6-overlay/releases/download/v${S6_VERSION}/s6-overlay-${ARCH}.tar.gz; \
        tar xzf /tmp/s6-overlay.tar.gz -C / --exclude="./bin" && \
    tar xzf /tmp/s6-overlay.tar.gz -C /usr ./bin; \
        apt-get autoremove -y wget

# Copy in s6 and prebuilt binaries
COPY root /
COPY --from=docker.io/grewhit25/debian-snapcast /usr/local/bin/snapclient /usr/local/bin/
COPY --from=builder /go/src/github.com/grewhit25/k8s-health-check/check /usr/local/bin/

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y \
    libasound2-plugins avahi-daemon flac \
    apulse libopus0 libvorbis0a libsoxr0 libavahi-client3 && \
    rm -rf /var/lib/apt/lists/* && \
    cp /defaults/client-run /etc/services.d/snapcast/run

ENTRYPOINT ["/init"]