FROM alpine:edge
LABEL MAINTAINER="Greg White grewhit25@gmail.com"

ENV TZ London/Europe

RUN apk -U upgrade -a && \
    apk add --no-cache \
    tzdata tini bash \
    flac opus \
    libvorbis \
    alsa-plugins-pulse \
    avahi-libs avahi dbus \
    snapcast-client \
    && \
    # setup timezone
    ln -s /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    apk del tzdata

# COPY --from=snapcast-v19-alpine /usr/local/bin/snapclient /usr/local/bin/
COPY entrypoint.sh /

# mounting dbus on host so avahi can work.
VOLUME /var/run/dbus

ENTRYPOINT [ "/sbin/tini", "--", "/entrypoint.sh" ]
CMD ["snapclient"]
