FROM golang as builder
#
# Install health check
# credit to https://github.com/meisterplan/k8s-health-check.git
RUN go get github.com/grewhit25/k8s-health-check
WORKDIR  /go/src/github.com/grewhit25/k8s-health-check
RUN make build

FROM ubuntu:20.04
# Install snapcast server
LABEL MAINTAINER="Greg White grewhit25@gmail.com"
# v0.20.1
ARG S6_VERSION='2.1.0.0'

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y wget 

# Install s6 overlay
RUN apt-get update && apt-get install -y \
    wget && \
    set -ex; \
    ARCH="$(uname -m)"; \
    if [ "$ARCH" = 'armv7l' ]; then ARCH='armhf'; \
    elif [ "$ARCH" = 'x86_64' ]; then ARCH='x86'; \
    fi; \
    wget --no-check-certificate -qO /tmp/s6-overlay.tar.gz https://github.com/just-containers/s6-overlay/releases/download/v${S6_VERSION}/s6-overlay-${ARCH}.tar.gz; \
        tar xzf /tmp/s6-overlay.tar.gz -C / --exclude="./bin" && \
    tar xzf /tmp/s6-overlay.tar.gz -C /usr ./bin; \
        apt-get autoremove -y wget

# Install dependences
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y avahi-daemon libavahi-client3 \
    libvorbisenc2 flac libopus0  libsoxr-dev libasound2-dev && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/* /var/tmp/* && \
    mkdir /health && touch /health/healthz

# Copy in s6 and prebuilt binaries
COPY root /
COPY --from=builder /go/src/github.com/grewhit25/k8s-health-check/check /usr/local/bin/
COPY --from=docker.io/grewhit25/debian-snapcast /usr/local/bin/snapserver /usr/local/bin/
COPY --from=docker.io/grewhit25/debian-librespot /usr/local/bin/librespot /usr/local/bin/

# Snapcast Ports
EXPOSE 1704 1705
VOLUME /output

ENTRYPOINT ["/init"]
