FROM ubuntu:focal


RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y tini avahi-daemon libavahi-client3 \
    libvorbisenc2 flac libopus0  && \
    rm -rf /var/lib/apt/lists/*

COPY --from=docker.io/grewhit25/debian-snapcast /usr/local/bin/snapserver /usr/local/bin/
COPY --from=docker.io/grewhit25/debian-snapcast /usr/local/bin/healthz /usr/local/bin/
COPY --from=docker.io/grewhit/docker-librespot /usr/local/bin/librespot /usr/local/bin/
COPY entrypoint.sh /
COPY *.conf /etc/

RUN chmod +x /entrypoint.sh

# Snapcast Ports
EXPOSE 1704 1705
VOLUME /output

ENTRYPOINT ["tini", "--", "/entrypoint.sh"]
CMD ["snapserver", "--config /etc/snapserver.conf"]