ARG LIBRESPOTIMAGE
FROM ${LIBRESPOTIMAGE} as librespot-image

FROM alpine:edge
# https://github.com/s1lvester/docker-snapcast-multiroomaudio/blob/master/Dockerfile

ENV TZ London/Europe
ARG LIBRESPOT

RUN apk -U upgrade -a && \
    apk add --no-cache \
    avahi-libs tzdata \
    tini bash libgcc \
    flac opus \
    libvorbis \
    llvm-libunwind \
    snapcast-server && \
    ln -s /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    apk del tzdata

# mounting dbus on host so avahi can work.
VOLUME /var/run/dbus /output

# Snapcast Ports
EXPOSE 1704 1705 1780

# Avahi port
EXPOSE 5353


COPY --from=librespot-image /usr/local/bin/librespot /usr/local/bin/
#COPY --from=librespot-rpi-010320 /usr/local/bin/librespot /usr/local/bin/
#COPY --from=snapcast-v19-alpine /usr/local/bin/snapserver /usr/local/bin/

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["snapserver"]
