FROM alpine:edge as builder

# Create server client from source

RUN apk -U add git bash build-base asio-dev soxr-dev \
    avahi-dev flac-dev libvorbis-dev alsa-lib-dev opus opus-dev

# Install Snapcast
WORKDIR /code
RUN git clone --recursive -b develop https://github.com/badaix/snapcast.git src && \
    cd src && \
    make

From alpine
# Copy out client and server binary

COPY --from=builder /code/src/server/snapserver /usr/local/bin/
COPY --from=builder /code/src/client/snapclient /usr/local/bin/

USER root